on:
  push:
    branches:
      - main
    paths:
      - "psl_stitch/**"
      - "api/**"
      - "Dockerfile"
      - ".github/workflows/**"
# Environment variables available to all jobs and steps in this workflow
env:
  CONTAINER_REPO: hdoupe
  IMAGE_NAME: psl-stitch-api

jobs:
  build:
    name: Build, push, and deploy api
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Build container image
        run: docker build -t registry.digitalocean.com/${CONTAINER_REPO}/${IMAGE_NAME}:$(echo $GITHUB_SHA | head -c7) .

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600

      - name: Push image to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/${CONTAINER_REPO}/${IMAGE_NAME}:$(echo $GITHUB_SHA | head -c7)
