name: Frontend Deploy

on:
  push:
    branches:
      - main
    paths:
      - "psl-stitch-app/**"
      - ".github/workflows/frontend-deploy.yaml"

env:
  CONTAINER_REPO: hdoupe
  IMAGE_NAME: psl-stitch-app
  CONTAINER_NAME: ${IMAGE_NAME}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Test, Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Build container image
        run: docker build -t registry.digitalocean.com/${CONTAINER_REPO}/${IMAGE_NAME}:$(echo $GITHUB_SHA | head -c7) .

      - name: Log in to DigitalOcean Container Registry
        run: doctl registry login --expiry-seconds 1200

      - name: Push image to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/${CONTAINER_REPO}/${IMAGE_NAME}:$(echo $GITHUB_SHA | head -c7)

      - name: Update service
        run: |
        doctl compute ssh ${{secrets.DIGITALOCEAN_DROPLET}} --ssh-command 'cd psl-stitch && git pull origin main'
        doctl compute ssh ${{secrets.DIGITALOCEAN_DROPLET}} --ssh-command 'cd psl-stitch && ./scripts/deploy.sh'
